### ISSUE TITLE
Can't build on Mac os 10.9.3

### ISSUE THREAD

**Issue by troglodisme** [edy555/homebrew-openlase#2]
Hi Edy555, 

I am trying to your use version of OpenLase for Mac, but failing to build it properly despite your very good instructions. This is what I get in the terminal in the last operation:

giulios-mbp-3:~ Giulio$ brew install openlase --HEAD
==> Cloning https://github.com/marcan/openlase.git
Cloning into '/Library/Caches/Homebrew/openlase--git'...
remote: Counting objects: 102, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 102 (delta 14), reused 56 (delta 3), pack-reused 0
Receiving objects: 100% (102/102), 3.33 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
==> Patching
patching file Modules/CMakeASM_YASMInformation.cmake
Hunk #1 succeeded at 1 with fuzz 2.
patching file examples/CMakeLists.txt
patching file libol/CMakeLists.txt
patching file libol/trace.c
patching file python/CMakeLists.txt
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 22 (offset 1 line).
1 out of 2 hunks FAILED -- saving rejects to file python/CMakeLists.txt.rej
patching file tools/CMakeLists.txt
Hunk #1 FAILED at 18.
1 out of 1 hunk FAILED -- saving rejects to file tools/CMakeLists.txt.rej
patching file tools/playilda.c
patching file tools/qplayvid/CMakeLists.txt
patching file tools/simulator.c
Error: Applying DATA patch failed
giulios-mbp-3:~ Giulio$ 

Can you please help me out?
Thanks a lot

**Comment by davidvondle** [comment]
try: "brew install openlase"
instead of using the --HEAD option.

**Comment by shoheisato** [comment]
Hi
How can I install OpenLase to OSX10.11?
I tried brew install openlase --HEAD 
but patching is failed
it says..

patching file Modules/CMakeASM_YASMInformation.cmake
Hunk #1 succeeded at 1 with fuzz 2.
patching file examples/CMakeLists.txt
patching file libol/CMakeLists.txt
patching file libol/trace.c
patching file python/CMakeLists.txt
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 22 (offset 1 line).
1 out of 2 hunks FAILED -- saving rejects to file python/CMakeLists.txt.rej
patching file tools/CMakeLists.txt
Hunk #1 FAILED at 18.
1 out of 1 hunk FAILED -- saving rejects to file tools/CMakeLists.txt.rej
patching file tools/playilda.c
patching file tools/qplayvid/CMakeLists.txt
patching file tools/simulator.c
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1

thanks
