### ISSUE TITLE
Can't build on OSX10.11 

### ISSUE THREAD

**Issue by katsuwo** [edy555/homebrew-openlase#3]
Hi.
I'm trying to build openlase on osx10.11 el capitan.
but 
"brew install openlase --HEAD" is failed to some patching process.
below is log.

----------------------------
==> Installing openlase from edy555/homebrew-openlase
==> Cloning https://github.com/marcan/openlase.git
Updating /Library/Caches/Homebrew/openlase--git
==> Checking out branch master
==> Patching
patching file Modules/CMakeASM_YASMInformation.cmake
Hunk #1 succeeded at 1 with fuzz 2.
patching file examples/CMakeLists.txt
patching file libol/CMakeLists.txt
patching file libol/trace.c
patching file python/CMakeLists.txt
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 22 (offset 1 line).
1 out of 2 hunks FAILED -- saving rejects to file python/CMakeLists.txt.rej
patching file tools/CMakeLists.txt
Hunk #1 FAILED at 18.
1 out of 1 hunk FAILED -- saving rejects to file tools/CMakeLists.txt.rej
patching file tools/playilda.c
patching file tools/qplayvid/CMakeLists.txt
patching file tools/simulator.c
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
----------------------------

and I tried to "brew install openlase" too.
below is log 

----------------------------
==> Installing openlase from edy555/homebrew-openlase
==> Cloning https://github.com/edy555/openlase.git
Updating /Library/Caches/Homebrew/openlase--git
==> Checking out branch ffmpeg_deprecated
==> Patching
patching file Modules/CMakeASM_YASMInformation.cmake
patching file examples/CMakeLists.txt
patching file libol/CMakeLists.txt
patching file libol/trace.c
patching file python/CMakeLists.txt
patching file tools/CMakeLists.txt
patching file tools/playilda.c
patching file tools/qplayvid/CMakeLists.txt
patching file tools/simulator.c
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_
Last 15 lines from /Users/katsuwo/Library/Logs/Homebrew/openlase/01.cmake:
-- Found FFMPEG: /usr/local/lib/libavcodec.dylib;/usr/local/lib/libavformat.dylib;/usr/local/lib/libavutil.dylib;/usr/local/lib/libavdevice.dylib /usr/local/include
-- Checking for module 'libswscale'
--   Found libswscale, version 3.1.101
-- Found Swscale: /usr/local/lib/libswscale.dylib  
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework  
-- Found GLUT: /usr/X11R6/lib/libglut.dylib  
-- Could NOT find ALSA (missing:  ALSA_LIBRARY ALSA_INCLUDE_DIR) 
-- Found Curses: /usr/lib/libcurses.dylib  
CMake Error at libol/CMakeLists.txt:20 (check_include_files):
  Unknown CMake command "check_include_files".

-- Configuring incomplete, errors occurred!
----------------------------

how can I fix it?

thanks

**Comment by taktran** [comment]
I'm having the same problem on El Capitan too - any progress in getting it working?

**Comment by edy555** [comment]
Please omit --HEAD option to install.

Fixed patch for building on El Capitan and updated README.md.
