### ISSUE TITLE
Cant install on osx 10.11.4

### ISSUE THREAD

**Issue by michaelterry** [edy555/homebrew-openlase#4]
on clean osx install
I have installed the prerequisites using homebrew

$ brew install cmake
$ brew install ffmpeg
$ brew install qt
$ brew install jack --build-from-source

brew install openlase fails with the following output

Michaels-MacBook-Pro:openlase michaelterry$ brew install openlase
==> Installing openlase from edy555/openlase
==> Cloning https://github.com/edy555/openlase.git
Updating /Library/Caches/Homebrew/openlase--git
==> Checking out branch ffmpeg_deprecated
==> Patching
patching file Modules/CMakeASM_YASMInformation.cmake
patching file examples/CMakeLists.txt
patching file libol/CMakeLists.txt
patching file libol/trace.c
patching file python/CMakeLists.txt
patching file tools/CMakeLists.txt
patching file tools/playilda.c
patching file tools/qplayvid/CMakeLists.txt
patching file tools/simulator.c
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEA
==> make
Last 15 lines from /Users/michaelterry/Library/Logs/Homebrew/openlase/02.make:
/usr/local/Library/ENV/4.3/clang  -O3 -g -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/openlase-circlescope.dir/circlescope.c.o  -o openlase-circlescope  -L/tmp/openlase20160326-2446-1abc7ue/libol  /usr/local/lib/libjack.dylib -lm -Wl,-rpath,/tmp/openlase20160326-2446-1abc7ue/libol
/tmp/openlase20160326-2446-1abc7ue/tools/playvid.c:136:16: error: no member named 'get_buffer' in 'struct AVCodecContext'
                        pACodecCtx->get_buffer(pACodecCtx, pAudioFrame);
                        ~~~~~~~~~~  ^
1 error generated.
make[2]: *** [tools/CMakeFiles/openlase-playvid.dir/playvid.c.o] Error 1
make[1]: *** [tools/CMakeFiles/openlase-playvid.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Built target openlase-scope
[ 70%] Built target openlase-circlescope
[ 72%] Linking CXX executable output
cd /tmp/openlase20160326-2446-1abc7ue/output && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E cmake_link_script CMakeFiles/output.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++   -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/output.dir/output.cpp.o CMakeFiles/output.dir/output_settings.cpp.o CMakeFiles/output.dir/moc_output_settings.cxx.o  -o output -F/usr/local/Cellar/qt/4.8.7_2/lib  /usr/local/lib/libjack.dylib -framework QtGui -framework QtCore
[ 72%] Built target output
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/edy555/homebrew-openlase/issues

**Comment by edy555** [comment]
fixed issue, pls try!

**Comment by michaelterry** [comment]
Works great thanks,

You are the best, lasers rule ❤️
